# Generated by Django 3.1.6 on 2021-02-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Helloworld',
        ),
    ]
