# Generated by Django 3.1.6 on 2021-02-12 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-pk']},
        ),
    ]
