# Generated by Django 3.1.6 on 2021-02-12 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_auto_20210212_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id']},
        ),
    ]
