# Generated by Django 3.1.6 on 2021-02-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_auto_20210212_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
    ]
